package jspectrumanalyzer.core;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.io.FileNotFoundException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FrequencyAllocations {

	private static final Logger LOG = LoggerFactory.getLogger(FrequencyAllocations.class);
	/** Classpath directory under which {@code freq/*.csv} and {@code freq/index.txt} live. */
	private static final String RESOURCE_DIR = "/freq/";
	/** Generated at build time; one file name per line. */
	private static final String INDEX_RESOURCE = RESOURCE_DIR + "index.txt";

	private final TreeMap<String, FrequencyAllocationTable> table = new TreeMap<>();

	public FrequencyAllocations() throws FileNotFoundException {
		loadAll();
	}

	public TreeMap<String, FrequencyAllocationTable> getTable() {
		return new TreeMap<>(table);
	}

	/**
	 * Load every CSV listed in {@code /freq/index.txt}. The index is generated by
	 * the {@code generateFreqIndex} Gradle task so we don't need to enumerate a
	 * directory on the classpath (unreliable when running from a jar).
	 */
	private void loadAll() throws FileNotFoundException {
		InputStream indexStream = FrequencyAllocations.class.getResourceAsStream(INDEX_RESOURCE);
		if (indexStream == null) {
			LOG.warn("'{}' missing on classpath; no allocation tables loaded.", INDEX_RESOURCE);
			return;
		}
		try (BufferedReader reader = new BufferedReader(
				new InputStreamReader(indexStream, StandardCharsets.UTF_8))) {
			String name;
			while ((name = reader.readLine()) != null) {
				name = name.trim();
				if (name.isEmpty()) continue;
				try (InputStream csv = FrequencyAllocations.class.getResourceAsStream(RESOURCE_DIR + name)) {
					if (csv == null) {
						LOG.warn("Missing resource {}{}", RESOURCE_DIR, name);
						continue;
					}
					loadTableFromCSV(name, csv);
				}
			}
		} catch (IOException e) {
			throw new FileNotFoundException("Failed to read " + INDEX_RESOURCE + ": " + e.getMessage());
		}
	}
	
	private void loadTableFromCSV(String locationName, InputStream is) {
		BufferedReader reader	= null;
		
		ArrayList<FrequencyBand> bands	= new ArrayList<>();
		
		try {
			/**
			 * Source:
			 * https://www.efis.dk/views2/search-general.jsp
			 */
			//"- Europe (ECA) -";"526.500 - 1606.500 kHz";"Broadcasting";"Inductive applications/Broadcasting"
			Pattern patternCSV	= Pattern.compile("\"[^\"]+\";\"([0-9.]+)\\s+-\\s+([0-9.]+)\\s+([kM])Hz\";\"([^\"]+)\";\"([^\"]+)\"");
			
			reader	= new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
			String line	= null;
			int lineNo	= 0;
			while((line = reader.readLine()) != null) {
				lineNo++;
				if (lineNo == 1)
					continue;
				
				Matcher m	= patternCSV.matcher(line);
				if (m.find()) {
					double multiplier	= m.group(3).equals("k") ? 1000 : 1000000;
					long startFreq	= Math.round(Double.parseDouble(m.group(1)) * multiplier);
					long stopFreq	= Math.round(Double.parseDouble(m.group(2)) * multiplier);
					String name	= m.group(4);
					String applications	= m.group(5);
					FrequencyBand band	= new FrequencyBand(startFreq, stopFreq, name, applications);
					bands.add(band);
				}
			}
			
		} catch (Exception e) {
			LOG.warn("Failed to parse allocation table {}", locationName, e);
			return;
		}
		finally {
			if (reader != null) {
				try {
					reader.close();
				} catch (IOException e) {
					
				}
			}
		}
		FrequencyAllocationTable allocationTable	= new FrequencyAllocationTable(locationName, bands);
		table.put(locationName, allocationTable);
	}
}
